[package]
name = "md_analyze"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1"
anyhow = "1"
regex = "1"
walkdir = "2"
colored = "2"
separator = "0.4"

[lib]
name = "md_analyze"
path = "src/mod.rs"

[[bin]]
name = "md_analyze"
path = "src/main.rs"